import {StyleSheet} from 'react-native';
import {colorPallete} from '../../components/atoms/colorPalette';
import {horizontalScale} from '../../components/atoms/constant';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    backgroundColor: colorPallete.mainColor,
    height: '50%',
    width: '200%',
    // borderRadius: 180,
    borderBottomEndRadius: 530,
    borderBottomStartRadius: 590,
    top: -150,
    right: -120,
  },
  report: {
    flex: 1,
    // backgroundColor: colorPallete.basicColor,
  },
  reportContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 3,
    marginTop: 15,
    marginBottom: 20,
  },
  analytics: {
    alignItems: 'center',
    width: '92%',
    borderRadius: 12,
    backgroundColor: colorPallete.backgroundColor,
    justifyContent: 'center',
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderWidth: 2,
    borderColor: 'white',
  },
  container1Text: {
    width: '65%',
    backgroundColor: colorPallete.backgroundColor,
    paddingLeft: horizontalScale(20),
  },
  font: {
    color: colorPallete.mainColor,
    fontSize: 22,
    fontWeight: '600',
  },
  fontSmall: {
    color: 'grey',
    fontSize: 16,
  },
  progressView: {
    width: '35%',
    alignItems: 'center',
    backgroundColor: colorPallete.backgroundColor,
  },
  percentage: {fontSize: 16, color: colorPallete.greenPercentageColor},
  color: colorPallete.greenPercentageColor,
  shadowColor: 'lightgrey',
  bgColor: colorPallete.basicColor,
  outerCircle: {bottom: 2},
  performance: {
    color: colorPallete.hightlightedColor,
    marginTop: 20,
    fontSize: 24,
    paddingTop: 10,
  },
  reportHeading: {
    flex: 0.5,
    marginHorizontal: 18,
    justifyContent: 'center',
    marginBottom: 10,
  },
  reportText: {
    fontSize: 20,
    fontWeight: '600',
    color: 'black',
    textAlign: 'left',
    fontFamily: 'roboto',
  },
  statistics: {
    marginTop: 10,
    marginBottom: 40,
    marginLeft: 40,
    marginRight: 40,
    borderRadius: 20,
    paddingBottom: 30,
    backgroundColor: '#EEEEEE',
  },
  header: {
    color: colorPallete.hightlightedColor,
    fontSize: 20,
    marginLeft: 10,
    marginTop: 10,
  },
  calenderIcon: {
    position: 'absolute',
    right: '16%',
    top: '1.5%',
  },
  lottie: {height: 40, width: 40},
  theme: {
    backgroundColor: 'yellow',
    calendarBackground: colorPallete.backgroundColor,
    textSectionTitleColor: '#b6c1cd',
    textSectionTitleDisabledColor: '#d9e1e8',
    selectedDayBackgroundColor: '#00adf5',
    selectedDayTextColor: '#ffffff',
    todayTextColor: '#00adf5',
    dayTextColor: '#2d4150',
    textDisabledColor: '#d9e1e8',
    dotColor: '#00adf5',
    selectedDotColor: '#ffffff',
    arrowColor: colorPallete.appColor,
    disabledArrowColor: '#d9e1e8',
    monthTextColor: 'blue',
    indicatorColor: 'blue',
    textDayFontFamily: 'monospace',
    textMonthFontFamily: 'monospace',
    textDayHeaderFontFamily: 'monospace',
    textDayFontWeight: '700',
    textMonthFontWeight: 'bold',
    textDayHeaderFontWeight: '800',
    textDayFontSize: 13,
    textMonthFontSize: 10,
    textDayHeaderFontSize: 14,
  },
  calendarView: {
    flex: 5.5,
    alignItems: 'center',
    marginBottom: 10,
  },
  calendar: {
    elevation: 6,
    borderRadius: 7,
    width: horizontalScale(320),
    backgroundColor: colorPallete.backgroundColor,
    borderWidth: 2,
    borderColor: 'white',
    paddingBottom: 10,
    // paddingHorizontal: 10,
  },
  modalHeader: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    padding: 10,
    flex: 1,
  },
  modalBox: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
  },
  modalContainer: {
    width: '98%',
    height: '75%',
    backgroundColor: colorPallete.basicColor,

    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colorPallete.appColor,
  },
  progressBar: {
    justifyContent: 'center',
    flex: 8,
    padding: 10,
    flexDirection: 'row',
    // alignItems:'center',
  },
  modalHeaderText: {
    fontSize: 20,
    color: colorPallete.appColor,
    fontWeight: '500',
  },
  modalSubHeader: {
    // justifyContent:'center',
    alignItems: 'center',
    flex: 2,
    margin: 15,
  },
  timeSlot: {
    backgroundColor: colorPallete.appColor,
    borderRadius: 70,
    width: '30%',
    height: '15%',
    justifyContent: 'center',
    alignItems: 'center',
    marginEnd: 10,
  },
  timeSlotText: {
    color: colorPallete.basicColor,
    fontSize: 20,
  },
  picker: {
    borderWidth: 2,
    borderColor: colorPallete.appColor,
    backgroundColor: colorPallete.basicColor,
    borderRadius: 10,
    marginHorizontal: 13,
    marginTop: 8,
  },
  picker: {
    borderWidth: 2,
    borderColor: colorPallete.appColor,
    backgroundColor: colorPallete.basicColor,
    borderRadius: 10,
    paddingHorizontal: 20,
  },
  timeText: {
    fontSize: 20,
    paddingLeft: 20,
    color: '#000',
  },
  takenText: {
    color: colorPallete.redColor,
    fontSize: 20,
    paddingLeft: 20,
    paddingTop: 10,
  },
});
