let apiUrl = 'https://f0c6-106-51-81-179.in.ngrok.io/api/v1/user';

export const LOGIN = `${apiUrl}/login`;
export const SIGN_UP = `${apiUrl}/sign-up`;
export const MY_PATIENTS = `${apiUrl}/my-patients`;
export const PATIENTS_REQUEST = `${apiUrl}/patient-requests`;
export const USER_MEDICINE = `${apiUrl}/medicines`;
export const GET_MY_CARETAKER =`${apiUrl}/my-caretakers`;
export const MY_CARETAKER_REQUEST = `${apiUrl}/caretaker-requests`; 
export const GET_MY_REMINDERS= `${apiUrl}/medicine-reminder`;
export const SAVE_MEDICINE = `${apiUrl}/save-medicine`
export const SAVE_DOCTOR_PRESCRIPTION = `${apiUrl}/save-doctor-prescription`;
export const USER_MEDICINE_BY_ID= `${apiUrl}/medicineById`;
export const EDIT_PROFILE = `${apiUrl}/user-details`;
export const ACCEPT_REQUEST = `${apiUrl}/accepted`;
export const SEND_SNAP = `${apiUrl}/image`;
export const DELETE_MEDICINE = `${apiUrl}/medicine/delete`;
export const APPOINTMENT_REMINDER=`${apiUrl}/doctor-prescriptions-name`;
export const SAVE_DOCTOR_APPOINTMENT = `${apiUrl}/create-doctor-appointment`;
export const GET_DOCTOR_APPOINTMENT = `${apiUrl}/doctor-appointments`;
export const GET_USER_MEDICINE=`${apiUrl}/medicines`
export const MY_PRESCRIPTIONS = `${apiUrl}/doctor-prescriptions`;
export const GET_USER = `${apiUrl}/id`;
export const GET_ALL_NOTIFICATION=`${apiUrl}/notification/get-notifications`
export const DELETE_NOTIFICATION=`${apiUrl}/notification/delete`

export const GET_ALL_PRESCRIPTION=`${apiUrl}/doctor-prescriptions`
export const SAVE_USER_MEDICINE=`${apiUrl}/medicine/save`
export const MY_CARETAKER = `${apiUrl}/my-caretakers`;
export const CARETAKER_REQUEST = `${apiUrl}/caretaker-requests`;
export const DELETE_REQUEST = `${apiUrl}/request-delete`;
