//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RESET_LOGIN = 'RESET_LOGIN';

//SIGNUP
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const RESET_SIGNUP = 'RESET_SIGNUP';

//EDIT PROFILE
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
export const RESET_PROFILE = 'RESET_PROFILE';

//MY PATIENTS
export const MY_PATIENTS_REQUEST = 'MY_PATIENTS_REQUEST';
export const MY_PATIENTS_SUCCESS = 'MY_PATIENTS_SUCCESS';
export const MY_PATIENTS_ERROR = 'MY_PATIENTS_ERROR';

//PATIENT REQUESTS
export const PATIENT_REQ_REQUEST = 'PATIENT_REQ_REQUEST';
export const PATIENT_REQ_SUCCESS = 'PATIENT_REQ_SUCCESS';
export const PATIENT_REQ_ERROR = 'PATIENT_REQ_ERROR';

//ACCEPT PATIENT REQUEST
export const ACCEPT_PATIENT_REQ_REQUEST = 'ACCEPT_PATIENT_REQUEST_REQUEST';
export const ACCEPT_PATIENT_REQ_SUCCESS = 'ACCEPT_PATIENT_REQUEST_SUCCESS';
export const ACCEPT_PATIENT_REQ_ERROR = 'ACCEPT_PATIENT_REQUEST_ERROR';

//DELETE PATIENT REQUEST
export const DELETE_PATIENT_REQ_REQUEST = 'DELETE_PATIENT_REQUEST_REQUEST';
export const DELETE_PATIENT_REQ_SUCCESS = 'DELETE_PATIENT_REQUEST_SUCCESS';
export const DELETE_PATIENT_REQ_ERROR = 'DELETE_PATIENT_REQUEST_ERROR';

//SEND SNAP
export const SEND_SNAP_REQUEST = 'SEND_SNAP_REQUEST';
export const SEND_SNAP_SUCCESS = 'SEND_SNAP_SUCCESS';
export const SEND_SNAP_ERROR = 'SEND_SNAP_ERROR';
