//LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RESET_LOGIN = 'RESET_LOGIN';

//SIGNUP
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const RESET_SIGNUP = 'RESET_SIGNUP';
//EDITPROFILE
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
//User medicine
export const USER_MEDICINE_SUCCESS = 'USER_MEDICINE_SUCCESS';
export const USER_MEDICINE_REQUEST = 'USER_MEDICINE_REQUEST';
export const USER_MEDICINE_ERROR = 'USER_MEDICINE_ERROR';
//CARETAKER REQUEST
export const MY_CARETAKER_REQUEST = 'MY_CARETAKER_REQUEST'
export const MY_CARETAKER_SUCCESS = 'MY_CARETAKER_SUCCESS'
export const MY_CARETAKER_ERROR = 'MY_CARETAKER_ERROR'
//CARETAKER REQUEST LIST
export const CARETAKER_LIST_REQUEST = 'CARETAKER_LIST_REQUEST'
export const CARETAKER_LIST_SUCCESS = 'CARETAKER_LIST_SUCCESS'
export const CARETAKER_LIST_ERROR = 'CARETAKER_LIST_ERROR'


