import {StyleSheet} from 'react-native';
import {colorPalette} from '../../components/atoms/colorPalette';
import {horizontalScale, verticalScale} from '../../components/atoms/constant';

export const styles = StyleSheet.create({
  background: {
    position: 'absolute',
    backgroundColor: colorPalette.mainColor,
    height: '50%',
    width: '200%',
    borderBottomEndRadius: 530,
    borderBottomStartRadius: 590,
    top: -120,
    right: -120,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#E8E8E8	',
  },
  card: {
    borderRadius: 20,
    borderColor: 'white',
    marginVertical: verticalScale(6),
    width: '92%',
    borderWidth: 2,
    shadowColor: 'black',
    elevation: 6,
    backgroundColor: colorPalette.backgroundColor,
    borderColor: 'white',
    marginBottom: 15,
    height: '40%',
  },
  progressCircleContainer: {
    alignItems: 'center',
    paddingBottom: verticalScale(12),
    backgroundColor: colorPalette.backgroundColor,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    height: verticalScale(150),
    width: '100%',
  },
  progressText: {fontSize: 20, fontWeight: '600', color: 'black'},
  font: {
    color: colorPalette.mainColor,
    fontSize: 22,
    marginHorizontal: horizontalScale(20),
    alignSelf: 'flex-start',
  },
  reminderView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    height: '4%',
  },
  circle: {
    borderWidth: 2,
    borderColor: 'lightgrey',
    borderRadius: 15,
    height: 20,
    width: 20,
    alignItems: 'center',
  },
  modal: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.3)',
  },
  modalOk: {
    fontSize: 15,
    color: 'black',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 10,
    padding: 4,
    paddingHorizontal: 5,
  },
  modalContainer: {
    backgroundColor: 'white',
    height: 155,
    width: '92%',
    borderRadius: 20,
    justifyContent: 'flex-start',
    padding: 10,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  modalTouch:{
    alignItems: 'flex-end',
    justifyContent: 'center',
    padding: 5,
    paddingHorizontal: 10,
  },
  modalHeading:{
    fontSize: 20,
    color: 'black',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  modalView: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    padding: 5,
    paddingHorizontal: 10,
  },
  info:{
    width: '15%',
    justifyContent: 'center',
  },
});
